// import { Shop, Product } from '@/types';

// export const mockShops: Shop[] = [
//   {
//     id: '1',
//     name: 'Keells Super',
//     address: 'Main Street, Colombo 03',
//     latitude: 6.9271,
//     longitude: 79.8612,
//     distance: 0.5,
//     isOpen: true,
//     rating: 4.5,
//     offers: ['10% off on groceries', 'Buy 2 Get 1 Free'],
//     category: 'Supermarket',
//     phone: '+94112345678',
//     image:
//       'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '2',
//     name: 'Cargills Food City',
//     address: 'Galle Road, Mount Lavinia',
//     latitude: 6.8344,
//     longitude: 79.8639,
//     distance: 1.2,
//     isOpen: true,
//     rating: 4.2,
//     offers: ['Fresh vegetables daily'],
//     category: 'Supermarket',
//     phone: '+94112345679',
//     image:
//       'https://images.pexels.com/photos/1005638/pexels-photo-1005638.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '3',
//     name: 'Arpico Supercentre',
//     address: 'Union Place, Colombo 02',
//     latitude: 6.9147,
//     longitude: 79.8549,
//     distance: 0.8,
//     isOpen: false,
//     rating: 4.3,
//     offers: [],
//     category: 'Supermarket',
//     phone: '+94112345680',
//     image:
//       'https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '4',
//     name: 'Local Grocery Store',
//     address: 'Colombo Road, Dehiwala',
//     latitude: 6.852,
//     longitude: 79.8698,
//     distance: 2.1,
//     isOpen: true,
//     rating: 4.0,
//     offers: ['Home delivery available'],
//     category: 'Grocery',
//     phone: '+94112345681',
//     image:
//       'https://images.pexels.com/photos/1005638/pexels-photo-1005638.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },

//   // New shops (IDs continue from 5)
//   {
//     id: '5',
//     name: 'Trendy Cuts Saloon',
//     address: 'Bambalapitiya, Colombo 04',
//     latitude: 6.9001,
//     longitude: 79.8593,
//     distance: 0.9,
//     isOpen: true,
//     rating: 4.3,
//     offers: ['Men’s haircut Rs. 1200 (Weekdays 10am–2pm)'],
//     category: 'Saloon',
//     phone: '+94112345682',
//     image:
//       'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '6',
//     name: 'Royal Salon & Spa',
//     address: 'Nugegoda',
//     latitude: 6.872,
//     longitude: 79.8911,
//     distance: 3.3,
//     isOpen: true,
//     rating: 4.7,
//     offers: ['Ladies haircut 15% off (Tue)'],
//     category: 'Saloon',
//     phone: '+94112345683',
//     image:
//       'https://images.pexels.com/photos/3993460/pexels-photo-3993460.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '7',
//     name: 'TechHub Electronics',
//     address: 'Kollupitiya, Colombo 03',
//     latitude: 6.9205,
//     longitude: 79.8533,
//     distance: 2.1,
//     isOpen: true,
//     rating: 4.6,
//     offers: ['Up to 20% on accessories'],
//     category: 'Electronics',
//     phone: '+94112345684',
//     image:
//       'https://images.pexels.com/photos/8205237/pexels-photo-8205237.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '8',
//     name: 'Electro World',
//     address: 'Maharagama',
//     latitude: 6.8403,
//     longitude: 79.9292,
//     distance: 6.1,
//     isOpen: true,
//     rating: 4.3,
//     offers: ['Audio fest up to 25%'],
//     category: 'Electronics',
//     phone: '+94112345685',
//     image:
//       'https://images.pexels.com/photos/1045299/pexels-photo-1045299.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '9',
//     name: 'SwiftFix Auto Care',
//     address: 'Kirulapone, Colombo 06',
//     latitude: 6.8902,
//     longitude: 79.871,
//     distance: 3.4,
//     isOpen: true,
//     rating: 4.4,
//     offers: ['Free checkup with oil change'],
//     category: 'Vehicle Repair',
//     phone: '+94112345686',
//     image:
//       'https://images.pexels.com/photos/3807305/pexels-photo-3807305.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '10',
//     name: 'Speedy Tyre & Service',
//     address: 'Kotte',
//     latitude: 6.9033,
//     longitude: 79.912,
//     distance: 4.6,
//     isOpen: false,
//     rating: 4.1,
//     offers: [],
//     category: 'Vehicle Repair',
//     phone: '+94112345687',
//     image:
//       'https://images.pexels.com/photos/6870432/pexels-photo-6870432.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '11',
//     name: 'HealthPlus Pharmacy',
//     address: 'Havelock Rd, Colombo 05',
//     latitude: 6.8841,
//     longitude: 79.8618,
//     distance: 1.1,
//     isOpen: true,
//     rating: 4.7,
//     offers: [],
//     category: 'Pharmacy',
//     phone: '+94112345688',
//     image:
//       'https://images.pexels.com/photos/3652092/pexels-photo-3652092.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '12',
//     name: 'City Care Pharmacy',
//     address: 'Kiribathgoda',
//     latitude: 6.9761,
//     longitude: 79.9222,
//     distance: 3.0,
//     isOpen: true,
//     rating: 4.2,
//     offers: [],
//     category: 'Pharmacy',
//     phone: '+94112345689',
//     image:
//       'https://images.pexels.com/photos/7619858/pexels-photo-7619858.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '13',
//     name: 'Sunrise Bakery',
//     address: 'Kollupitiya, Colombo 03',
//     latitude: 6.9268,
//     longitude: 79.864,
//     distance: 0.5,
//     isOpen: true,
//     rating: 4.2,
//     offers: ['Buy 1 Get 1 on buns (5–7pm)'],
//     category: 'Bakery',
//     phone: '+94112345690',
//     image:
//       'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '14',
//     name: 'Sweet Crust Bakery',
//     address: 'Nawala',
//     latitude: 6.8882,
//     longitude: 79.9034,
//     distance: 3.8,
//     isOpen: true,
//     rating: 4.1,
//     offers: [],
//     category: 'Bakery',
//     phone: '+94112345691',
//     image:
//       'https://images.pexels.com/photos/140831/pexels-photo-140831.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '15',
//     name: 'GreenLeaf Organics',
//     address: 'Nugegoda',
//     latitude: 6.8721,
//     longitude: 79.8943,
//     distance: 2.7,
//     isOpen: false,
//     rating: 4.1,
//     offers: [],
//     category: 'Grocery',
//     phone: '+94112345692',
//     image:
//       'https://images.pexels.com/photos/2983098/pexels-photo-2983098.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '16',
//     name: 'Veggie Basket',
//     address: 'Wellawatte',
//     latitude: 6.8677,
//     longitude: 79.8619,
//     distance: 1.2,
//     isOpen: true,
//     rating: 4.6,
//     offers: ['Combo veg packs Rs. 999'],
//     category: 'Grocery',
//     phone: '+94112345693',
//     image:
//       'https://images.pexels.com/photos/4199091/pexels-photo-4199091.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '17',
//     name: 'Quick Mobile Repair',
//     address: 'Borella',
//     latitude: 6.9142,
//     longitude: 79.8775,
//     distance: 2.0,
//     isOpen: true,
//     rating: 4.0,
//     offers: ['Screen guard free with screen replace'],
//     category: 'Mobile Repair',
//     phone: '+94112345694',
//     image:
//       'https://images.pexels.com/photos/6078128/pexels-photo-6078128.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '18',
//     name: 'Book Nook',
//     address: 'Colombo 07',
//     latitude: 6.9107,
//     longitude: 79.8744,
//     distance: 4.2,
//     isOpen: true,
//     rating: 4.5,
//     offers: [],
//     category: 'Bookstore',
//     phone: '+94112345695',
//     image:
//       'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '19',
//     name: 'ToolTown Hardware',
//     address: 'Dehiwala',
//     latitude: 6.8401,
//     longitude: 79.8655,
//     distance: 3.7,
//     isOpen: true,
//     rating: 4.1,
//     offers: [],
//     category: 'Hardware',
//     phone: '+94112345696',
//     image:
//       'https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '20',
//     name: 'Style Street Clothing',
//     address: 'Colombo 05',
//     latitude: 6.8892,
//     longitude: 79.8539,
//     distance: 2.9,
//     isOpen: false,
//     rating: 4.0,
//     offers: [],
//     category: 'Clothing',
//     phone: '+94112345697',
//     image:
//       'https://images.pexels.com/photos/3965545/pexels-photo-3965545.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '21',
//     name: 'Bean & Brew Cafe',
//     address: 'Colombo 03',
//     latitude: 6.9244,
//     longitude: 79.8615,
//     distance: 0.9,
//     isOpen: true,
//     rating: 4.6,
//     offers: ['20% off 3–5pm (Mon–Fri)'],
//     category: 'Cafe',
//     phone: '+94112345698',
//     image:
//       'https://images.pexels.com/photos/374885/pexels-photo-374885.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '22',
//     name: 'HomeChoice Appliances',
//     address: 'Nawala',
//     latitude: 6.8982,
//     longitude: 79.9002,
//     distance: 5.8,
//     isOpen: true,
//     rating: 4.3,
//     offers: [],
//     category: 'Home Appliances',
//     phone: '+94112345699',
//     image:
//       'https://images.pexels.com/photos/1202247/pexels-photo-1202247.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '23',
//     name: 'Fresh Cuts Butchery',
//     address: 'Wellawatte',
//     latitude: 6.8729,
//     longitude: 79.8601,
//     distance: 2.4,
//     isOpen: true,
//     rating: 4.4,
//     offers: [],
//     category: 'Butcher',
//     phone: '+94112345700',
//     image:
//       'https://images.pexels.com/photos/3186654/pexels-photo-3186654.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '24',
//     name: 'Dairy Delights',
//     address: 'Colombo 04',
//     latitude: 6.8931,
//     longitude: 79.8621,
//     distance: 1.6,
//     isOpen: true,
//     rating: 4.5,
//     offers: ['10% on cheese platters'],
//     category: 'Dairy Shop',
//     phone: '+94112345701',
//     image:
//       'https://images.pexels.com/photos/533360/pexels-photo-533360.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '25',
//     name: 'Happy Paws Pet Shop',
//     address: 'Battaramulla',
//     latitude: 6.9022,
//     longitude: 79.9482,
//     distance: 4.9,
//     isOpen: false,
//     rating: 4.5,
//     offers: [],
//     category: 'Pet Shop',
//     phone: '+94112345702',
//     image:
//       'https://images.pexels.com/photos/7210758/pexels-photo-7210758.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
//   {
//     id: '26',
//     name: 'Stationery Corner',
//     address: 'Bambalapitiya',
//     latitude: 6.8977,
//     longitude: 79.8586,
//     distance: 2.5,
//     isOpen: true,
//     rating: 4.0,
//     offers: ['Back-to-school 15% off'],
//     category: 'Stationery',
//     phone: '+94112345703',
//     image:
//       'https://images.pexels.com/photos/5088009/pexels-photo-5088009.jpeg?auto=compress&cs=tinysrgb&w=800',
//   },
// ];

// export const mockProducts: Product[] = [
//   {
//     id: '1',
//     name: 'Basmati Rice 5kg',
//     price: 1200,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Rice & Grains',
//     image:
//       'https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.5,
//     distance: 0.5,
//   },
//   {
//     id: '2',
//     name: 'Fresh Milk 1L',
//     price: 180,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/236010/pexels-photo-236010.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'L',
//     rating: 4.3,
//     distance: 0.5,
//   },
//   {
//     id: '3',
//     name: 'Red Onions 1kg',
//     price: 220,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'low_stock',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/533342/pexels-photo-533342.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.1,
//     distance: 1.2,
//   },
//   {
//     id: '4',
//     name: 'Chicken Breast 500g',
//     price: 750,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Meat',
//     image:
//       'https://images.pexels.com/photos/616401/pexels-photo-616401.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.4,
//     distance: 0.5,
//   },
//   {
//     id: '5',
//     name: 'Green Beans 250g',
//     price: 120,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/1359326/pexels-photo-1359326.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.0,
//     distance: 2.1,
//   },
//   {
//     id: '6',
//     name: 'Bread Loaf',
//     price: 95,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'out_of_stock',
//     category: 'Bakery',
//     image:
//       'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'piece',
//     rating: 4.2,
//     distance: 1.2,
//   },
//   {
//     id: '7',
//     name: 'Eggs 12 Pack',
//     price: 420,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/162712/eggs-egg-carton-chicken-eggs-food-162712.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'pack',
//     rating: 4.6,
//     distance: 0.5,
//   },
//   {
//     id: '8',
//     name: 'Sunflower Oil 1L',
//     price: 950,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Oils',
//     image:
//       'https://images.pexels.com/photos/461382/pexels-photo-461382.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'L',
//     rating: 4.2,
//     distance: 1.2,
//   },
//   {
//     id: '9',
//     name: 'Tomatoes 1kg',
//     price: 180,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'out_of_stock',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/839725/pexels-photo-839725.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.0,
//     distance: 0.8,
//   },
//   {
//     id: '10',
//     name: 'Butter 250g',
//     price: 350,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'low_stock',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/533360/pexels-photo-533360.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.3,
//     distance: 0.5,
//   },
//   {
//     id: '11',
//     name: 'Apples 1kg',
//     price: 520,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Fruits',
//     image:
//       'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.1,
//     distance: 2.1,
//   },
//   {
//     id: '12',
//     name: 'Orange Juice 1L',
//     price: 300,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Beverages',
//     image:
//       'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'L',
//     rating: 4.4,
//     distance: 1.2,
//   },
//   {
//     id: '13',
//     name: 'Potatoes 1kg',
//     price: 150,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/41957/potatoes-potato-basket-food-41957.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.2,
//     distance: 0.8,
//   },
//   {
//     id: '14',
//     name: 'Chicken Eggs 6 Pack',
//     price: 220,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'out_of_stock',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/162712/eggs-egg-carton-chicken-eggs-food-162712.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'pack',
//     rating: 4.0,
//     distance: 2.1,
//   },
//   {
//     id: '15',
//     name: 'Bananas 1kg',
//     price: 200,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Fruits',
//     image:
//       'https://images.pexels.com/photos/461208/pexels-photo-461208.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.3,
//     distance: 0.5,
//   },
//   {
//     id: '16',
//     name: 'Coconut Oil 500ml',
//     price: 350,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Oils',
//     image:
//       'https://images.pexels.com/photos/461382/pexels-photo-461382.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'ml',
//     rating: 4.1,
//     distance: 1.2,
//   },
//   {
//     id: '17',
//     name: 'Carrots 1kg',
//     price: 180,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'out_of_stock',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/65174/pexels-photo-65174.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.0,
//     distance: 0.8,
//   },
//   {
//     id: '18',
//     name: 'Cheese 200g',
//     price: 600,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'low_stock',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/533360/pexels-photo-533360.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.5,
//     distance: 0.5,
//   },
//   {
//     id: '19',
//     name: 'Grapes 500g',
//     price: 350,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Fruits',
//     image:
//       'https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.2,
//     distance: 2.1,
//   },
//   {
//     id: '20',
//     name: 'Mango Juice 1L',
//     price: 320,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Beverages',
//     image:
//       'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'L',
//     rating: 4.4,
//     distance: 1.2,
//   },
//   {
//     id: '21',
//     name: 'Pumpkin 1kg',
//     price: 120,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/209339/pexels-photo-209339.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.1,
//     distance: 0.8,
//   },
//   {
//     id: '22',
//     name: 'Brown Bread',
//     price: 110,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Bakery',
//     image:
//       'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'piece',
//     rating: 4.2,
//     distance: 0.5,
//   },
//   {
//     id: '23',
//     name: 'White Bread',
//     price: 100,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'out_of_stock',
//     category: 'Bakery',
//     image:
//       'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'piece',
//     rating: 4.0,
//     distance: 1.2,
//   },
//   {
//     id: '24',
//     name: 'Spinach 250g',
//     price: 90,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/161519/pexels-photo-161519.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.3,
//     distance: 0.8,
//   },
//   {
//     id: '25',
//     name: 'Papaya 1kg',
//     price: 180,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Fruits',
//     image:
//       'https://images.pexels.com/photos/461208/pexels-photo-461208.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.1,
//     distance: 2.1,
//   },
//   {
//     id: '26',
//     name: 'Milk Powder 400g',
//     price: 650,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'low_stock',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/236010/pexels-photo-236010.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.5,
//     distance: 0.5,
//   },
//   {
//     id: '27',
//     name: 'Cucumber 1kg',
//     price: 140,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/161519/pexels-photo-161519.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.2,
//     distance: 1.2,
//   },
//   {
//     id: '28',
//     name: 'Pineapple 1kg',
//     price: 300,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'available',
//     category: 'Fruits',
//     image:
//       'https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.3,
//     distance: 0.8,
//   },
//   {
//     id: '29',
//     name: 'Chicken 1kg',
//     price: 1200,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Meat',
//     image:
//       'https://images.pexels.com/photos/616401/pexels-photo-616401.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.4,
//     distance: 2.1,
//   },
//   {
//     id: '30',
//     name: 'Beef 1kg',
//     price: 1800,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'out_of_stock',
//     category: 'Meat',
//     image:
//       'https://images.pexels.com/photos/616401/pexels-photo-616401.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.3,
//     distance: 0.5,
//   },
//   {
//     id: '31',
//     name: 'Lettuce 250g',
//     price: 70,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/161519/pexels-photo-161519.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.1,
//     distance: 1.2,
//   },
//   {
//     id: '32',
//     name: 'Oranges 1kg',
//     price: 400,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'available',
//     category: 'Fruits',
//     image:
//       'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.2,
//     distance: 0.8,
//   },
//   {
//     id: '33',
//     name: 'Yogurt 80g',
//     price: 60,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/533360/pexels-photo-533360.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.0,
//     distance: 2.1,
//   },
//   {
//     id: '34',
//     name: 'Green Peas 500g',
//     price: 160,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/1359326/pexels-photo-1359326.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.2,
//     distance: 0.5,
//   },
//   {
//     id: '35',
//     name: 'Apple Juice 1L',
//     price: 280,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Beverages',
//     image:
//       'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'L',
//     rating: 4.3,
//     distance: 1.2,
//   },
//   {
//     id: '36',
//     name: 'Eggplant 1kg',
//     price: 170,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'out_of_stock',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/65174/pexels-photo-65174.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.0,
//     distance: 0.8,
//   },
//   {
//     id: '37',
//     name: 'Chicken Sausage 250g',
//     price: 350,
//     shopId: '4',
//     shopName: 'Local Grocery Store',
//     availability: 'available',
//     category: 'Meat',
//     image:
//       'https://images.pexels.com/photos/616401/pexels-photo-616401.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.1,
//     distance: 2.1,
//   },
//   {
//     id: '38',
//     name: 'Butter 100g',
//     price: 180,
//     shopId: '1',
//     shopName: 'Keells Super',
//     availability: 'available',
//     category: 'Dairy',
//     image:
//       'https://images.pexels.com/photos/533360/pexels-photo-533360.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.2,
//     distance: 0.5,
//   },
//   {
//     id: '39',
//     name: 'Tomato Sauce 400g',
//     price: 220,
//     shopId: '2',
//     shopName: 'Cargills Food City',
//     availability: 'available',
//     category: 'Condiments',
//     image:
//       'https://images.pexels.com/photos/839725/pexels-photo-839725.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'g',
//     rating: 4.1,
//     distance: 1.2,
//   },
//   {
//     id: '40',
//     name: 'Cabbage 1kg',
//     price: 120,
//     shopId: '3',
//     shopName: 'Arpico Supercentre',
//     availability: 'available',
//     category: 'Vegetables',
//     image:
//       'https://images.pexels.com/photos/161519/pexels-photo-161519.jpeg?auto=compress&cs=tinysrgb&w=400',
//     unit: 'kg',
//     rating: 4.2,
//     distance: 0.8,
//   },
// ];
